### ISSUE TITLE
Opening Bookmarks On Enter Key Doesn't Work

### ISSUE THREAD

**Issue by idanmid15** [alyssaxuu/omni#39]
```
VM27 content.js:201 Uncaught TypeError: Cannot read properties of undefined (reading 'ctrlKey')
    at handleAction (VM27 content.js:201:12)
    at HTMLDocument.<anonymous> (VM27 content.js:305:4)
    at HTMLDocument.dispatch (jquery.js:2:43064)
    at HTMLDocument.v.handle (jquery.js:2:41048)
```
Looks like the event in handleAction is always undefined

**Comment by alyssaxuu** [comment]
Fixed, will be live soon.
